name: 'dbt_demo'
version: '1.0.0'

profile: 'dbt_demo'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  dbt_demo:
    staging:
      +materialized: view
      +schema: staging
    marts:
      +materialized: table
      +schema: marts
